### ISSUE TITLE
GetTransactions not working

### ISSUE THREAD

**Issue by ssuriyayuvan** [EdgeApp/edge-react-gui#2863]
In edge currency monero `getTransaction()` function is not working. I have no idea where i need to track this. Please update where the `gettransaction()` going and when it was called. I'm confused with getTransaction() function in xmrEngine.js and in same file `checkTransactionsInnerLoop()` this function is called. Please tell me the purpose of calling this inner loop function. for the reason transction history is not showing.

**Comment by ssuriyayuvan** [comment]
I'm getting error when open `gettransaction()`

```
at Object.onTransactionsChanged (file:///android_asset/edge-core/edge-core.js:2:612812)\n    at t.value (file:///android_asset/edge-core/plugin-bundle.js:61:320042)\n    at t.<anonymous> (file:///android_asset/edge-core/plugin-bundle.js:61:321189)\n    at l (file:///android_asset/edge-core/plugin-bundle.js:15:1472434)\n    at Generator._invoke (file:///android_asset/edge-core/plugin-bundle.js:15:1472187)\n    at Generator.forEach.e.<computed> [as next] (file:///android_asset/edge-core/plugin-bundle.js:15:1472791)\n    at r (file:///android_asset/edge-core/plugin-bundle.js:8:20221)\n    at s (file:///android_asset/edge-core/plugin-bundle.js:8:20432)\n    at file:///android_asset/edge-core/plugin-bundle.js:8:20491\n    at new Promise (<anonymous>)'
```

**Comment by ssuriyayuvan** [comment]
Found a solution this one was occur in xmrEngine.js `Date.parse(tx.time) / 1000` return NaN
