### ISSUE TITLE
postinstall.js failing due to Detox framework 

### ISSUE THREAD

**Issue by socialcode-rob1** [EdgeApp/edge-react-gui#978]
When performing **yarn** on a clean install, I encounter a Detox framework issues.  

**Command:** node scripts/postinstall.js

**Arguments:**
Directory: /edge-react-gui/node_modules/detox

**Output:**
/Library/Detox/ios/3b8bf121e33a47a46e6d2ca92c7d743d2d56b3cf was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Library/Detox/ios/3b8bf121e33a47a46e6d2ca92c7d743d2d56b3cf and trying to rebuild.
Extracting Detox sources...
Building Detox.framework from /edge-react-gui/node_modules/detox/ios_src...
child_process.js:644
    throw err;
    ^

Error: Command failed: /edge-react-gui/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.<anonymous> (/edge-react-gui/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Environment Details** 
MacOS Mojave 10.14
Xcode 10
NodeJS 8.11.3
NPM 6.4.1
Yarn 1.10.1
Java 1.8.0_181

**Comment by rsoutar** [comment]
Update detox in package.json to `"detox": "^9.0.6"` and run `yarn` again.
